export PLATFORM                = asap7
export CORNER                  = TC
export DESIGN_NAME             = attacc_fp16_add_lane_unit
export DESIGN_NICKNAME         = attacc_fp16_add_lane_666mhz
export VERILOG_FILES           = $(abspath rtl/attacc_fp16_pkg.sv) $(abspath rtl/attacc_fp16_operators.sv) $(abspath rtl/attacc_fp16_power_microbench.sv)
export SDC_FILE                = $(abspath openroad/constraint_fp16_lane_666mhz.sdc)
export SYNTH_HDL_FRONTEND      = slang
export VERILOG_DEFINES         = -D OPENROAD_CLKGATE
override export DONT_USE_CELLS = SDF* ICG*
export SYNTH_ARGS              = -noalumacc -noshare
export ADDER_MAP_FILE          =
export ABC_AREA                = 1
export CORE_UTILIZATION        = 60
export CORE_ASPECT_RATIO       = 1
export CORE_MARGIN             = 1.0
export PLACE_DENSITY           = 0.65
export TNS_END_PERCENT         = 100
export GPL_TIMING_DRIVEN       = 0
export GPL_ROUTABILITY_DRIVEN  = 0
