create_clock -name core_clk -period 1500 [get_ports clk]
create_generated_clock -name vector_gclk -source [get_ports clk] -divide_by 1 [get_nets -regexp {.*(gclk|GCK).*}]
set_clock_uncertainty -setup 50 [get_clocks core_clk]
set_clock_uncertainty -hold 0 [get_clocks core_clk]
set_clock_uncertainty -setup 50 [get_clocks vector_gclk]
set_clock_uncertainty -hold 0 [get_clocks vector_gclk]
set_input_delay 0.000 -clock core_clk [get_ports {state_reset tile_valid tile_last tile_head_id tile_state_reset score_data activation_valid activation_silu activation_data}]
set_output_delay 0.000 -clock core_clk [all_outputs]
set_false_path -from [get_ports rst_n]
