create_clock -name core_clk -period 1500 [get_ports clk]
create_generated_clock -name accum_gclk -source [get_ports clk] -divide_by 1 [get_nets -regexp {.*g_lane_add.*gclk.*}]
create_generated_clock -name accum_state_gclk -source [get_ports clk] -divide_by 1 [get_nets state_gclk]
set_clock_uncertainty -setup 50 [get_clocks core_clk]
set_clock_uncertainty -hold 0 [get_clocks core_clk]
set_clock_uncertainty -setup 50 [get_clocks accum_gclk]
set_clock_uncertainty -hold 0 [get_clocks accum_gclk]
set_clock_uncertainty -setup 50 [get_clocks accum_state_gclk]
set_clock_uncertainty -hold 0 [get_clocks accum_state_gclk]
set_input_delay 0.000 -clock core_clk [get_ports {partial_valid partial_slot partial_clear partial_last partial_data}]
set_output_delay 0.000 -clock core_clk [all_outputs]
set_false_path -from [get_ports rst_n]
