#!/usr/bin/env python3
"""Generate zero-delay functional ASAP7 models for Yosys gate simulation.

This is intentionally not a timing model.  It extracts Boolean output
functions from the exact ASAP7 Liberty views used by ORFS and emits only the
standard-cell types instantiated by a supplied mapped netlist.  The result is
used to create an activity VCD; delay and power still come from OpenROAD.
"""

from __future__ import annotations

import argparse
import gzip
import re
from pathlib import Path


CELL_RE = re.compile(r"^\s*([A-Za-z][A-Za-z0-9_]*_ASAP7_75t_R)\s+[A-Za-z0-9_]+\s*\(", re.M)
CELL_START_RE = re.compile(r"\bcell\s*\(\s*([A-Za-z0-9_]+)\s*\)\s*\{")
PIN_START_RE = re.compile(r"\bpin\s*\(\s*([A-Za-z0-9_]+)\s*\)\s*\{")


def brace_block(text: str, start: int) -> str:
    """Return the braced block beginning at the opening brace at/after start."""
    opening = text.index("{", start)
    depth = 0
    for index in range(opening, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[opening + 1 : index]
    raise ValueError("unterminated Liberty block")


def liberty_text(path: Path) -> str:
    if path.suffix == ".gz":
        with gzip.open(path, "rt", encoding="utf-8") as source:
            return source.read()
    return path.read_text(encoding="utf-8")


def verilog_expr(liberty_expr: str) -> str:
    expr = liberty_expr.replace("*", "&").replace("+", "|")
    return re.sub(r"!\s*", "~", expr)


def parse_cells(liberty_files: list[Path], wanted: set[str]) -> dict[str, tuple[list[str], list[str], dict[str, str]]]:
    cells: dict[str, tuple[list[str], list[str], dict[str, str]]] = {}
    for filename in liberty_files:
        text = liberty_text(filename)
        for match in CELL_START_RE.finditer(text):
            name = match.group(1)
            if name not in wanted or name in cells:
                continue
            cell = brace_block(text, match.start())
            inputs: list[str] = []
            outputs: list[str] = []
            functions: dict[str, str] = {}
            for pin_match in PIN_START_RE.finditer(cell):
                pin = pin_match.group(1)
                pin_block = brace_block(cell, pin_match.start())
                direction = re.search(r"\bdirection\s*:\s*(input|output)\s*;", pin_block)
                if not direction:
                    continue
                if direction.group(1) == "input":
                    inputs.append(pin)
                else:
                    outputs.append(pin)
                    function = re.search(r'\bfunction\s*:\s*"([^"]+)"\s*;', pin_block)
                    if function:
                        functions[pin] = verilog_expr(function.group(1))
            if inputs or outputs:
                cells[name] = (inputs, outputs, functions)
    return cells


def manual_models() -> str:
    return """// Sequential cells need state; the Liberty Boolean functions cover combinational cells.\n\
module DFFHQNx1_ASAP7_75t_R (QN, D, CLK); output reg QN; input D, CLK; always @(posedge CLK) QN <= ~D; endmodule\n\
module DFFASRHQNx1_ASAP7_75t_R (QN, D, RESETN, SETN, CLK);\n\
  output reg QN; input D, RESETN, SETN, CLK;\n\
  always @(posedge CLK or negedge RESETN or negedge SETN)\n\
    if (!RESETN) QN <= 1'b1; else if (!SETN) QN <= 1'b0; else QN <= ~D;\n\
endmodule\n\
module ICGx1_ASAP7_75t_R (GCLK, ENA, SE, CLK);\n\
  output GCLK; input ENA, SE, CLK; reg enable_latched;\n\
  always @(CLK or ENA or SE) if (!CLK) enable_latched = ENA | SE;\n\
  assign GCLK = CLK & enable_latched;\n\
endmodule\n\n"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--netlist", type=Path, required=True)
    parser.add_argument("--liberty-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    wanted = set(CELL_RE.findall(args.netlist.read_text(encoding="utf-8")))
    manual = {"DFFHQNx1_ASAP7_75t_R", "DFFASRHQNx1_ASAP7_75t_R", "ICGx1_ASAP7_75t_R"}
    parsed = parse_cells(list(args.liberty_dir.glob("*.lib*")), wanted - manual)
    missing = sorted(wanted - manual - set(parsed))
    if missing:
        raise SystemExit("Missing Liberty functions for: " + ", ".join(missing))

    lines = ["// Generated by tools/generate_asap7_functional_models.py.\n", manual_models()]
    for name in sorted(parsed):
        inputs, outputs, functions = parsed[name]
        if set(outputs) != set(functions):
            raise SystemExit(f"Cell {name} has non-combinational or missing output function")
        ports = outputs + inputs
        lines.append(f"module {name} ({', '.join(ports)});")
        lines.append("  output " + ", ".join(outputs) + ";")
        if inputs:
            lines.append("  input " + ", ".join(inputs) + ";")
        for output in outputs:
            lines.append(f"  assign {output} = {functions[output]};")
        lines.append("endmodule\n")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(parsed) + len(manual)} functional cells to {args.output}")


if __name__ == "__main__":
    main()
